name: Sync App to Package Repo

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout App Repo (Source)
        uses: actions/checkout@v4
        with:
          path: source-repo

      - name: Checkout Package Repo (Destination)
        uses: actions/checkout@v4
        with:
          repository: UTHSC-Zhang/RMSTdesign-Package
          token: ${{ secrets.PAT }}
          path: dest-repo

      - name: Sync files to the package's inst/shiny_app directory
        run: |
          # Create the target directory if it doesn't exist
          mkdir -p ./dest-repo/inst/shiny_app/
          
          # Use rsync to copy all app files into the specified folder
          rsync -av --delete ./source-repo/ ./dest-repo/inst/shiny_app/

      - name: Commit and push changes to the package repo
        run: |
          cd dest-repo
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Exit if there are no changes to commit
          if -z "$(git status --porcelain)"; then
            echo "No changes to commit."
            exit 0
          fi

          git add .
          git commit -m "Automated sync of Shiny app files"
          git push






