name: Sync R files to RMSTSS-Package

on:
  push:
    paths:
      - 'R/**'  # Trigger only when any file in R/ changes

jobs:
  sync-r-folder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout RMSTSS-App repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Clone RMSTSS-Package repo
        env:
          TOKEN: ${{ secrets.PACKAGE_REPO_TOKEN }}
        run: |
          git clone https://x-access-token:${TOKEN}@github.com/UTHSC-Zhang/RMSTSS-Package.git

      - name: Sync R/ folder from App to Package
        run: |
          rsync -av --delete R/ RMSTSS-Package/R/

  
